FROM registry.access.redhat.com/ubi8/openjdk-21
ENV JAVA_APP_DIR=/deployments
LABEL org.label-schema.description="Spring Boot - HTTP Example" org.label-schema.version=2.3.2-1-SNAPSHOT org.label-schema.schema-version=1.0 org.label-schema.build-date=2022-05-25T07:32:41.736 org.label-schema.name="Spring Boot - HTTP Example" org.label-schema.url=https://www.snowdrop.dev/rest-http
EXPOSE 8080 8778 9779
COPY maven /deployments/